name: Docker Image CI

on:
  push:
    branches: [master, testing]
    paths:
      - Dockerfile-bookworm
      - Dockerfile-trixie
  pull_request:
    branches: [master, testing]
  schedule:
    - cron: "0 0 * * 6"
  workflow_dispatch:

env:
  registry: unixerius
  image: proxmox-qdevice
  platforms: linux/amd64,linux/arm64

jobs:

  build:

    runs-on: ubuntu-latest

    environment:
      name: ${{ github.ref_name }}

    strategy:
      matrix:
        debianver: [bookworm, trixie]
      fail-fast: false

    permissions:
      contents: read
      packages: write
      attestations: write

    steps:
    - name: Checkout sources
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      if: ${{ github.actor != 'dependabot[bot]' && !github.event.pull_request.head.repo.fork }}
      with:
        username: ${{ secrets.DHI_USER }}
        password: ${{ secrets.DHI_TOKEN }}

    - name: Login to Docker Hardened Images registry
      uses: docker/login-action@v3
      if: ${{ github.actor != 'dependabot[bot]' && !github.event.pull_request.head.repo.fork }}
      with:
        registry: dhi.io
        username: ${{ secrets.DHI_USER }}
        password: ${{ secrets.DHI_TOKEN }}

    - name: Login to GitHub Docker registry
      uses: docker/login-action@v3
      if: ${{ github.actor != 'dependabot[bot]' && !github.event.pull_request.head.repo.fork }}
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        # list of Docker images to use as base name for tags
        images: |
          ${{ env.registry }}/${{ env.image }}
          ghcr.io/${{ env.registry }}/${{ env.image }}
        tags: |
          type=raw,priority=1000,value=${{matrix.debianver}}
          type=schedule,priority=800,pattern={{date 'YYYYMMDD'}},prefix=${{matrix.debianver}}-
          type=sha,priority=400,prefix=${{matrix.debianver}}-
        flavor: |
          latest=auto

    - name: Build and push the Docker image
      id: docker_build
      if: ${{ github.actor != 'dependabot[bot]' && github.event_name != 'pull_request' }}
      uses: docker/build-push-action@v6
      with:
        push: ${{ vars.IMAGEPUSH }}
        provenance: mode=max,version=v1
        sbom: true
        platforms: ${{env.platforms}}
        file: Dockerfile-${{matrix.debianver}}
        #tags: ${{ steps.meta.outputs.tags }}
        tags: |
          ${{env.registry}}/${{env.image}}:${{matrix.debianver}}
          ghcr.io/${{env.registry}}/${{env.image}}:${{matrix.debianver}}

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}

  provenance-dockerhub:
    needs: [build]
    if: ${{ vars.IMAGEPUSH == 'true' }}
    permissions:
      actions: read # for detecting the Github Actions environment.
      id-token: write # for creating OIDC tokens for signing.
      packages: write # for uploading attestations.
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@v1.4.0
    with:
      image: ${{ needs.build.outputs.tag }}
      digest: ${{ needs.build.outputs.digest }}
      registry-username: ${{ secrets.DHI_USER }}
    secrets:
      registry-password: ${{ secrets.DHI_TOKEN }}

  provenance-gcr:
    needs: [build]
    if: ${{ vars.IMAGEPUSH == 'true' }}
    permissions:
      actions: read # for detecting the Github Actions environment.
      id-token: write # for creating OIDC tokens for signing.
      packages: write # for uploading attestations.
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@v1.4.0
    with:
      image: ${{ needs.build.outputs.tag }}
      digest: ${{ needs.build.outputs.digest }}
      registry-username: ${{ github.actor }}
    secrets:
      registry-password: ${{ secrets.GITHUB_TOKEN }}


